name         'ugns-common'
version      '0.1.0'
source       'https://github.com/jbouse/puppet-common.git'
author       'ugns'
license      'Apache License, Version 2.0'
summary      'Collection of common resources'
description  'A collection of common resources, classes and defines'
project_page 'https://github.com/jbouse/puppet-common'
